### ISSUE TITLE
unused filter in options 

### ISSUE THREAD

**Issue by HenryQW** [d5039m/national-rail-darwin#9]
Hi Matthew,

Thanks for the great wrapper. 

I noticed `filter` option is never used when building the request, `destination` is used for `filterCrs` instead.

https://github.com/mattsalt/national-rail-darwin/blob/282b0e23c87d11134ed7dee5f111add7dbece5e5/requestBuilder.js#L8

https://github.com/mattsalt/national-rail-darwin/blob/282b0e23c87d11134ed7dee5f111add7dbece5e5/templates.js#L12

https://github.com/mattsalt/national-rail-darwin/blob/282b0e23c87d11134ed7dee5f111add7dbece5e5/templates.js#L20

The options will have to be passed in as `destination` to get the desired response.

```js
rail.getDepartureBoardWithDetails('RDG', { filter: 'WAT' }, (e, result) => {
});

// instead I used ⬇️

rail.getDepartureBoardWithDetails('RDG', { destination: 'WAT' }, (e, result) => {
});
```

**Comment by mattsalt** [comment]
Hi Henry,

Glad you like it. I hope it's been useful. You make an excellent point, I shall get that tidied up as it could cause some confusion especially as the README references 'filter' and not 'destination'.

Thank you for the extremely detailed issue description!

Cheers,
Matt
